# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cee474a38dc49634ac48d1e05fdef56061c6afc8c1674e85d55713c6ce38eae0e695474d243a1c0469c22727feb94cad55d33b44afd7d50803d87262a98ec93

test:
  secret_key_base: 35d72c839d75f5e7f3b9681557a5fcaa4dc9cfe66269a4b292101593071c5c9272f481d57972bf647a4b22be9ac76299d91ef5881abf4ca2e6fe7477d8b9b32b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
